### ISSUE TITLE
Movie's metadata not showing on side-bar 

### ISSUE THREAD

**Issue by 1sma31L** [megadrive/stremio-letterboxd#34]
![Screenshot from 2024-07-04 01-58-56](https://github.com/megadrive/stremio-letterboxd/assets/68449500/4238d8c7-adec-4402-9cf9-f247e102ec8a)

**Comment by megadrive** [comment]
I removed the additional metadata for the hosted version as I was sending many megabytes per request, making the hosting bill quite high.

I'll add a flag in the environment variables to support sending full details for those who wish to add it to their hosted versions.

**Comment by megadrive** [comment]
Feature added in de000d8a6ebabe7e16ddecc8672462839e76dc90
