### ISSUE TITLE
Dont show imdb number, duration, etc... strange behavior

### ISSUE THREAD

**Issue by 9acca9** [megadrive/stremio-letterboxd#37]
Hi.
thanks for the addon. 
I just finally put it to work today. And it is working fine except because just show the imdb puntuation and duration of the movie for just a second.... and then hide, strange it seems.

i have the .env file like this:
root@letterboxd:~/stremio-letterboxd# cat .env
```
## Environment variables

# Have a look at /src/env.ts for more info and any defaults.

# You can use any database that Prisma supports.
# See docs:
# - https://www.prisma.io/docs/orm/prisma-schema/overview
DATABASE_URL=file:./db.sqlite
# The Node environment. Without quotes, set to "production" or "development". Defaults to "development" if unset.
NODE_ENV=production

ADDON_MAX_PAGES_FETCHED=35 # about 980 movies

ADDON_FULL_METADATA=true # true or false
DEBUG=letterboxd:*
```
And here there is a video that show what im talking about:
https://imgur.com/gallery/why-LSd0A2i

What could be happening here?
Thanks!

**Comment by 9acca9** [comment]
Oh. Now is working perfectly! for me is real important the "full metadata".
It was my user... it seems that it was broken, from testing things like... "delete cinemeta addon"...
Thanks for share your work!

p.s: i put the letterboxd in a url to make it accesible for stremio (like https://letterboxd.mydomian.com). It seems stremio dont like just http://192.168.0.10/manifest.json Do you know if it is possible to run the addon like that? Thanks!

**Comment by megadrive** [comment]
Stremio requires it to be https unless it's run locally, I think the only whitelisted local URLs are localhost and 127.0.0.1

If you want https on your local network that's beyond my knowledge and scope of the issues for this add-on. I'd google something along the lines of "local network https server" and see what it comes back with
